# Generated by Django 5.1.1 on 2024-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description',models.TextField()),
                ('imageurl', models.CharField(max_length=50)),
                ('date',models.DateField()),
                ('isActive',models.BooleanField()),
            ],
        ),
    ]
