# Generated by Django 5.1.4 on 2024-12-21 10:07

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category_alter_course_slug_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
